package com.abztrakinc.ABZPOS.ADMIN;

import android.Manifest;
import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.net.Uri;
import android.os.Environment;
import android.util.Log;
import android.widget.Toast;

import androidx.core.app.ActivityCompat;
import androidx.core.content.ContextCompat;
import androidx.core.content.FileProvider;

import java.io.File;
import java.util.ArrayList;

public class admin_email_send {





    private static final int PICK_FILE_REQUEST_CODE = 100;

    public void admin_email_send(Activity activity ,String FinalDate) {
        try {
            Log.e("please","\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n tngina");
            ArrayList<Uri> uris = new ArrayList<>();

            // Replace characters in the date string
            String dateForJournal = FinalDate.replaceAll("[/-]", "");

            // Create file object
            File file = new File(Environment.getExternalStorageDirectory() + "/ANDROID_POS/Consolidate/" + dateForJournal + "_Consolidate.txt");

            // Check if permission is granted to access external storage
            if (ContextCompat.checkSelfPermission(activity, Manifest.permission.READ_EXTERNAL_STORAGE) != PackageManager.PERMISSION_GRANTED) {
                // Permission is not granted, request it from the user
                ActivityCompat.requestPermissions(activity, new String[]{Manifest.permission.READ_EXTERNAL_STORAGE}, PICK_FILE_REQUEST_CODE);
            } else {
                // Permission is granted, proceed with accessing the file
                // Generate a content URI for the file
                Uri uri = Uri.fromFile(file);
                uris.add(uri);

                // Call the email sending task
                admin_send_email_async sendEmailTask = new admin_send_email_async();
                sendEmailTask.SendEmailTask(activity.getApplicationContext(), "bobwendelarcon@gmail.com", "ABZPOS GENERATED EMAIL", "This File is generated by Abzpos for testing", uris);
                sendEmailTask.execute();
                Log.d("EMAILSTATUS", "SEND SUCCESSFUL");
            }
        } catch (Exception ex) {
          //  Toast.makeText(activity, ex.toString(), Toast.LENGTH_SHORT).show();
            Log.d("EMAIL STATUS :", "SEND FAILED " + ex.getMessage());
        }
    }


//    public void sendEmail(android.databinding.tool.Context context, String FinalDate) {
//        this.contexts = context;
//        // Manually specify the path of the item
//        Log.d("EMAIL STATUS :","SEND SUCCESFUL");
//        Toast.makeText(, "TANGINA", Toast.LENGTH_SHORT).show();
//
////            File LocalConsolidate = new File(Environment.getExternalStorageDirectory()+"/ANDROID_POS/Consolidate");
////            if (!LocalConsolidate.exists()){
////                LocalConsolidate.mkdirs();
////            }
//        try {
//            String dateForJournal = FinalDate.replaceAll("[/-]", "");
//            // File file = new File(LocalConsolidate, dateForJournal + "_Consolidate.txt");
//            Uri uri = Uri.parse(Environment.getExternalStorageDirectory() + "/ANDROID_POS/Consolidate/" + dateForJournal + "_Consolidate.txt");
//
//            // Create a list of URIs containing only the manually specified URI
//            ArrayList<Uri> uris = new ArrayList<>();
//            uris.add(uri);
//
//            // Create and execute the email sending task
//            admin_send_email_async sendEmailTask = new admin_send_email_async();
//            sendEmailTask.SendEmailTask(activity.getApplicationContext(), "bobwendelarcon@gmail.com", "ABZPOS GENERATED EMAIL", "This File is generated by Abzpos for testing", uris);
//            sendEmailTask.execute();
//            Log.d("EMAIL STATUS :","SEND SUCCESFUL");
//        }
//        catch (Exception ex){
//            Toast.makeText(activity, ex.toString(), Toast.LENGTH_SHORT).show();
//            Log.d("EMAIL STATUS :","SEND FAILED");
//        }
//    }


}
